spring:
  profiles:
    active:
      -dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: sc-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001-dev.com:7001/eureka

---

server:
  port:8202
spring:
  profiles:test
  application:
    name:sc-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001-test.com:7001/eureka